import { Product } from './types';

const withMargin = (cost: number) => Number((cost * 1.3).toFixed(2));
const driveImage = (id: string) => `https://drive.google.com/thumbnail?id=${id}&sz=w1200`;

export const PRODUCTS: Product[] = [
  {
    id: 'cam-v380',
    name: 'Camera V380',
    description: 'Kamera pemantauan untuk rumah, pejabat dan projek keselamatan dengan paparan katalog sebenar.',
    costPrice: 160,
    sellingPrice: 208,
    category: 'Security',
    image: driveImage('1ZmlKjzZ7U2vRcJsWd7Q0uZleMNkm05IN'),
    gallery: [
      driveImage('1ZmlKjzZ7U2vRcJsWd7Q0uZleMNkm05IN'),
      driveImage('1jkHLxyaauu6vitEaKr-LfmWNz9ct-kVj'),
      driveImage('1qWqrXDsBC4352qylyazg8VRJWIeG0BCl'),
      driveImage('1Xfc4YsqvhLMgxVphTMZtgeQZeDjVYB98'),
      driveImage('1RK4uXnbCXb_ld8PImMYbJ0jkbAwfoaV3'),
      driveImage('1sB2NjBzrLAHtFO5oFiVlHE68T8V9sAa9'),
      driveImage('1XWZWXrmvy6jgIihHvnXPXl44GZABKZOF'),
      driveImage('1i4EBudfKmWhGmGuxzsIwdLT58LO--sPf'),
      driveImage('119_GwAc0FzgZqzdqWN-Hn0sueWJvAzlr'),
      driveImage('1wmQmhHZCzWooIQE0OA4_20iJbOrurnSQ'),
      driveImage('1SeEIUbb2vxCoKAyfwQwNV5fNjo9hPMKB'),
      driveImage('182Uwn1Vui_j8LwsGGz1XCxwimVHMPwS5'),
      driveImage('1iomC4xco9KA1vEfzwth7Ge7kGJm91MZH'),
    ],
    sku: 'CAM-V380',
    stockLabel: 'Stok aktif',
    badge: 'Best Seller',
    shopifyVariantId: '',
  },
  {
    id: 'siren-12v',
    name: 'Siren 12V 1 Tone',
    description: 'Siren amaran bunyi kuat untuk sistem alarm rumah, premis dan panel keselamatan.',
    costPrice: 19,
    sellingPrice: 24.7,
    category: 'Security',
    image: driveImage('1JnOtxiOgh1vRRJbhi_s_VkYu_PMm8c-u'),
    gallery: [
      driveImage('1JnOtxiOgh1vRRJbhi_s_VkYu_PMm8c-u'),
      driveImage('12k6QA2YEk_a_lm7CGxgpDOW5q9S9juQn'),
      driveImage('1MQmdtltNyIP8b6NM4Xn1iUw0-11gU1gk'),
      driveImage('1V0Ht8ohfJdBc83fVrWyDLh2ESZqlmWgH'),
      driveImage('1hjaxWOs-BlbfeEa57SxqDwcy2UJQsY6a'),
      driveImage('1imbcMW9DIB0LIYvn4oabXWNERT1J3D45'),
    ],
    sku: 'SIR-12V',
    stockLabel: 'Ready stock',
    badge: 'Alarm',
    shopifyVariantId: '',
  },
  {
    id: 'motion-12v',
    name: 'Motion Sensor 12V',
    description: 'Sensor gerakan untuk alarm automation, lampu trigger dan sistem keselamatan asas.',
    costPrice: 15,
    sellingPrice: 19.5,
    category: 'Security',
    image: driveImage('18WjjY_nwUznGJxDsa1Li8NIxxjn4MO8G'),
    gallery: [
      driveImage('18WjjY_nwUznGJxDsa1Li8NIxxjn4MO8G'),
      driveImage('1EZMk00cAFPOi7tCsT5ckkKkDapI6Geiy'),
      driveImage('16MdyiI2DoquM6IGc91C4JgCzU68at1zj'),
      driveImage('1Dj428OQcO1jRuQiwoFeK6kV15KzcvZxr'),
      driveImage('1zv8O4ji0-FR8yovGc0UE5NWwHVVEet33'),
      driveImage('1fy7Q9x_dbstWQ32MtuHRl991bkUeIPYt'),
      driveImage('1KKHgVFV_pGO9dMR-eC2bmuq9Ys7AhwO-'),
    ],
    sku: 'SEN-12V',
    stockLabel: 'Ready stock',
    badge: 'Sensor',
    shopifyVariantId: '',
  },
  {
    id: 'solar-panel',
    name: 'Solar Panel',
    description: 'Panel solar untuk setup tenaga ringan, sistem luar grid dan pemasangan lapangan.',
    costPrice: 85,
    sellingPrice: 110.5,
    category: 'Solar',
    image: driveImage('1lrdslzvVtI2l_HpXjAGgF9fulvVSwbls'),
    gallery: [
      driveImage('1lrdslzvVtI2l_HpXjAGgF9fulvVSwbls'),
      driveImage('17teYb8Hu87_JZ1xh1IEuCqXUXdm0OjRB'),
      driveImage('1UoHD8ZQV8yTGV5y-ygw2akxpLuG9kKQL'),
      driveImage('1Udv3xO-uy5D8EIW0_BWnI205-AMqFYJB'),
      driveImage('1tLQMIW1tgarr3x2ts0gWXpTVUzOixyAz'),
      driveImage('1_S5WeCXcO7zKp1MluiZMbMrZyPbASzoD'),
      driveImage('1XaUu37t2w6R6GW21BR3A4Re7TRsRg55h'),
      driveImage('1eD3hWPXqrqcQQH3mSmF6GDbxXaoFzCsS'),
      driveImage('1JAHwcJ-tydAgE3UPFn7-27pAqLo_PMEW'),
    ],
    sku: 'SOL-PANEL',
    stockLabel: 'Perlu semak stok',
    badge: 'Solar',
    shopifyVariantId: '',
  },
  {
    id: 'solar-charge',
    name: 'Solar Charge Controller',
    description: 'Charge controller untuk membantu kestabilan aliran kuasa dari panel ke bateri.',
    costPrice: 31,
    sellingPrice: 40.3,
    category: 'Solar',
    image: driveImage('1By6Yr7eo-wyRk66ocTB7UVCcFn2VpJyL'),
    gallery: [
      driveImage('1By6Yr7eo-wyRk66ocTB7UVCcFn2VpJyL'),
      driveImage('1y3efAMLhpRbBywuzvqVmzNDRnVLqTz5X'),
      driveImage('1vaSdEBEjXktvRsue0SBVivV4S54e3szK'),
      driveImage('1LFUevFSRJbVuVW0SXRduxlpsHCihRmRA'),
      driveImage('1RepJ3UkvPty2DGlVDuDNSN1b76GxnPBg'),
      driveImage('1tPEuWG80Huc9VUB9sIYSG5mKkXr5gEZM'),
      driveImage('1F9LvKAlUAfcPjab8TXFHWi477hd6cqo1'),
    ],
    sku: 'SOL-CTRL',
    stockLabel: 'Stok aktif',
    badge: 'Power',
    shopifyVariantId: '',
  },
  {
    id: 'battery-12ah',
    name: 'Battery 12Ah 12V',
    description: 'Bateri simpanan kuasa untuk backup supply, siren, solar dan panel controller.',
    costPrice: 54,
    sellingPrice: 70.2,
    category: 'Solar',
    image: driveImage('1HpTY3c05N0BDmQsZT7nx5SGuFEagwOP8'),
    gallery: [
      driveImage('1HpTY3c05N0BDmQsZT7nx5SGuFEagwOP8'),
      driveImage('1Ey-EkSpbazoHEocrlCAPGr0e0kwHG6kE'),
      driveImage('1_qP_4rdsJNa2U24lhaY_xg4DeM_tQnKS'),
      driveImage('1QmyNQqs2EzxorzTMZgWVtKylJd5JDKOt'),
      driveImage('1hzmG8GvaumnwvvBJbMMB999Zb8R3BnMz'),
      driveImage('14L5tANIEKG6GcqZ4ARXsFrsjBn-PTeQC'),
    ],
    sku: 'BAT-12AH',
    stockLabel: 'Ready stock',
    badge: 'Battery',
    shopifyVariantId: '',
  },
  {
    id: 'drawer-lock',
    name: 'Drawer Key Lock',
    description: 'Kunci laci dan kabinet untuk panel box, stor peralatan dan enclosure.',
    costPrice: 2,
    sellingPrice: 2.6,
    category: 'Accessories',
    image: driveImage('127W11AEVsGWpndSBcKdg57PK6G6IM7N5'),
    gallery: [
      driveImage('127W11AEVsGWpndSBcKdg57PK6G6IM7N5'),
      driveImage('1LtzO4H2BBBj71ta8coSlU2hxD1-0vwwR'),
      driveImage('1wZyLZWcTUdOYMrM-L9sx7BBcOgHMtxpJ'),
      driveImage('1GJFtDxD7auR6vMcnB6e-o8vyYy6QXf-d'),
      driveImage('187CQvwQi9ztAQ-JkvK2w1vOyLqtdJyR5'),
      driveImage('1LFgOFor_tiUq1pvQeXlBSQb_5yHSo4YG'),
      driveImage('1SxGzaqBDwQi7sUYAYaNTeR78ziMenUH2'),
      driveImage('1Rr_O4TnYShvWLpdXrlVt04EWo1s99HhB'),
      driveImage('1eaElpZ4jn4V28eOJ3QeE3Xetw7plTsbN'),
    ],
    sku: 'LOCK-DRW',
    stockLabel: 'Stok aktif',
    badge: 'Hardware',
    shopifyVariantId: '',
  },
  {
    id: 'switch',
    name: 'Switch',
    description: 'Switch serbaguna untuk kawalan sistem, trigger aksesori dan pemasangan am.',
    costPrice: 2.5,
    sellingPrice: 3.25,
    category: 'Accessories',
    image: driveImage('1CnE5ohS4U92CJInsTiifzcbvrbKcdWYX'),
    gallery: [
      driveImage('1CnE5ohS4U92CJInsTiifzcbvrbKcdWYX'),
      driveImage('1ZTVbHkA7U3LArV0WPOvA0n2X8wdM5b_i'),
      driveImage('1wSBIsxFb4XX9I8bT3szqWDugNg50ZXe0'),
      driveImage('1g_JCGMN15BHzk6nwfeHWEfdXjtaIK2Ir'),
      driveImage('1MHB25a_je_EeWNW-kMeSnHOPApfqR7li'),
    ],
    sku: 'SWT-GEN',
    stockLabel: 'Ready stock',
    badge: 'Electrical',
    shopifyVariantId: '',
  },
  {
    id: 'cable-18awg',
    name: 'Cable 18AWG',
    description: 'Kabel low voltage sesuai untuk wiring projek keselamatan dan sambungan aksesori.',
    costPrice: 2.5,
    sellingPrice: 3.25,
    category: 'Accessories',
    image: driveImage('1j7TZMJIBjBW7TG2F1YrFhtwADYnC0fu-'),
    gallery: [
      driveImage('1j7TZMJIBjBW7TG2F1YrFhtwADYnC0fu-'),
      driveImage('1KqScr3-02UXMep6q_oxNRkb9hnGx6ZlH'),
      driveImage('1ovnosFwsrGgKf8gkvd-36ZJ4evbYBzKJ'),
      driveImage('1QMpQrWMfUJ9hxL0mLZiT07k-nLugHwNa'),
      driveImage('1mMAUVAlq8NCUr-lHTC0pXthvPl2G9zUD'),
    ],
    sku: 'CBL-18AWG',
    stockLabel: 'Ready stock',
    badge: 'Cable',
    shopifyVariantId: '',
  },
  {
    id: 'l-bracket',
    name: 'L Bracket',
    description: 'Bracket sokongan untuk mounting panel, enclosure dan pemasangan aksesori.',
    costPrice: 3,
    sellingPrice: 3.9,
    category: 'Accessories',
    image: driveImage('1SzpyA2-AZdKXMOXN4eVmIm9M_FmbCW6t'),
    gallery: [
      driveImage('1SzpyA2-AZdKXMOXN4eVmIm9M_FmbCW6t'),
      driveImage('1MgXv0sVA96Ok8FldmTvfBNmmR1mQNNM4'),
      driveImage('162DcuLXYqIfr-gHUQw9E20SnijBy24Fn'),
      driveImage('1ksoXOjp7VRSz_5_KFz2qGqqHL3vwwMtM'),
      driveImage('1n_yvzDy7UpR0lasuPl6Ns92xmN9GtFlz'),
    ],
    sku: 'L-BRACKET',
    stockLabel: 'Stok aktif',
    badge: 'Mounting',
    shopifyVariantId: '',
  },
  {
    id: 'geb-box',
    name: 'GEB Metal Outdoor Box',
    description: 'Outdoor metal enclosure untuk controller, wiring box dan projek di kawasan luar.',
    costPrice: 85,
    sellingPrice: withMargin(85),
    category: 'Accessories',
    image: driveImage('16-VpKPUxi7yKX2Yzc7zv9wIum5r-ew8J'),
    gallery: [
      driveImage('16-VpKPUxi7yKX2Yzc7zv9wIum5r-ew8J'),
      driveImage('1pRZN9osfjQZFDm5yZnIqV3BMGlnlFED8'),
      driveImage('1FaypfM-zHhUpuTAgyjmYEkyIZgt3I9kk'),
      driveImage('1mtV9pkUyS2d-GUtq_iYUhM7Agt4Idzvo'),
      driveImage('1H0LDfQNTy36j2IWxm2u95rDDTeujwOfQ'),
    ],
    sku: 'BOX-GEB',
    stockLabel: 'Pre-order',
    badge: 'Enclosure',
    shopifyVariantId: '',
  },
];

export const BUSINESS_INFO = {
  name: 'Izwan Systec Enterprise',
  regNo: '202103055724',
  businessNo: 'CA0318484-D',
  bank: 'CIMB Bank Berhad',
  accountNo: '8604630283',
  email: 'izwansystec@gmail.com',
  phone: '+60 11-XXXX XXXX',
  location: 'Malaysia',
  whatsappNumber: import.meta.env.VITE_WHATSAPP_NUMBER || '60174511455',  // +6017-4511455
  whatsappLinkFallback: 'https://wa.me/',
  shopifyStoreUrl: import.meta.env.VITE_SHOPIFY_STORE_URL || '',
  shopifyStorefrontAccessToken: import.meta.env.VITE_SHOPIFY_STOREFRONT_ACCESS_TOKEN || '',
  shopifyStorefrontApiVersion: import.meta.env.VITE_SHOPIFY_STOREFRONT_API_VERSION || '2026-01',
  shopifyCartPath: '/cart/',
  duitNowQrUrl: import.meta.env.VITE_DUITNOW_QR_URL || '',  // Optional: URL imej QR DuitNow merchant dari bank
};

export const PAYMENT_OPTIONS = [
  {
    id: 'shopify',
    title: 'Shopify Checkout',
    description: 'Buka checkout Shopify sebenar melalui Storefront API. Perlu VITE_SHOPIFY_STORE_URL dan variant ID produk.',
    status: 'Perlu setup',
  },
  {
    id: 'fpx',
    title: 'FPX / Debit / Credit Card',
    description: 'Tersedia melalui Shopify bila gateway FPX diaktifkan. Buat masa ini guna DuitNow sebagai alternatif.',
    status: 'Perlu setup',
  },
  {
    id: 'duitnow',
    title: 'DuitNow / Bank Transfer',
    description: 'Transfer terus ke CIMB 8604630283. Hantar bukti bayaran ke WhatsApp admin selepas bayar.',
    status: 'Sedia',
  },
  {
    id: 'whatsapp',
    title: 'Order via WhatsApp',
    description: 'Pesanan lengkap dengan item, jumlah dan alamat dihantar terus ke WhatsApp admin untuk closing manual.',
    status: 'Sedia',
  },
] as const;

export const TESTIMONIALS = [
  {
    name: 'Ahmad Razif',
    location: 'Selangor',
    quote: 'Gambar produk nampak lebih yakin dan pelanggan terus nampak cara bayar yang jelas.',
  },
  {
    name: 'Nurul Faizah',
    location: 'Johor Bahru',
    quote: 'Checkout dengan WhatsApp sangat membantu sementara payment gateway penuh belum siap.',
  },
  {
    name: 'Zulhilmi Hassan',
    location: 'Kedah',
    quote: 'Susun atur baru lebih kemas dan nampak macam storefront sebenar, bukan sekadar katalog asas.',
  },
];
